#!/usr/bin/perl

# realm - REmote Authentication Log Monitor
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2014 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#

use warnings;
use strict;

use DBI;
use Geo::IP;
use Getopt::Std;
use Net::Whois::Raw;

my $VERSION = qq(0.1);
$Getopt::Std::STANDARD_HELP_VERSION++;

sub HELP_MESSAGE {
    print <<USG;
Usage:

  realm-feed [-v] [-c <cfg>]

    -v		be more verbose
    -c <cfg>	config filename

USG
}

sub VERSION_MESSAGE {
    print <<LIC;

realm $VERSION - REmote Authentication Log Monitor

Authors:
  Thomas Liske <thomas\@fiasko-nw.net>

Copyright Holder:
  2014 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]

Upstream:
  https://github.com/liske/realm

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

LIC
#/
}

our %realmconf = (
    ds => ['dbi:SQLite:dbname=/var/lib/realm/backend', '', ''],
);

our $opt_c = '/etc/realm/realm.conf';
our $opt_v;
unless(getopts('c:v')) {
    HELP_MESSAGE;
    exit 1;
}

die "ERROR: Could not read config file '$opt_c'!\n" unless(-r $opt_c);

# slurp config file
eval `cat "$opt_c"`;
die "$@\n" if($@);

my $dbh = DBI->connect(@{$realmconf{ds}});
my $gi = Geo::IP->new(GEOIP_INDEX_CACHE | GEOIP_CHECK_CACHE);

$Net::Whois::Raw::OMIT_MSG = 1;
$Net::Whois::Raw::CHECK_FAIL = 1;

while(<STDIN>) {
    chomp;

    my ($in_ip, $in_user, $in_host, $in_service, $in_misc) = split(/\|/);
    $in_host ||= 'localhost';
    $in_service ||= '<unknown>';
    $in_misc ||= '-';

    my $whois = whois($in_ip);
    my $asn = -1;
    my $netname = '<unknown>';

    $asn = $1 if($whois =~ /^origin\S*:\s+(AS\d+)/mi);
    $netname = $1 if($whois =~ /^netname:\s+(\S+)/mi);

    my %dataset = (
	host => $in_host,
	service => $in_service,
	country => $gi->country_code_by_addr($in_ip),
	asn => $asn,
	netname => $netname,
    );

    use Data::Dumper;
    print Dumper(\%dataset);
}
